name: Check Linked Issues
'on':
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    name: Check linked issues
    permissions:
      issues: read
      pull-requests: write
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude-branches: release/**, dependabot/**
